[package]
name = "ruql"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
itertools = "0.10.3"
num-bigint = "0.4.3"
pest = "2.1.3"
pest_derive = "2.1.0"
rusqlite = "0.27.0"
rustyline = "9.1.2"
structopt = "0.3.26"

[features]
